name: env-torch
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - pip:
      - torchaudio --index-url https://download.pytorch.org/whl/cpu